 cmake_policy(VERSION 3.16.1)
 #needs TT_TARGET_DIR variable set to location of .exe
 #finds and copies mono dll to TT_TARGET_DIR
function(FindMon MONO_ROOT)
    set(PATHETIC_PATHS $ENV{PATH})
    LIST(APPEND PATHETIC_PATHS "C:\\Program Files")
    LIST(APPEND PATHETIC_PATHS "C:\\Program Files (x86)")
    set(FOUND OFF)
    set(OUT "")
    foreach(pathe IN ITEMS ${PATHETIC_PATHS})
        #message("Searching for mono ${pathe}")
         if("${pathe}" MATCHES "Mono(\\|/|)$")
            message("Found mono ${pathe}")
            set(OUT "${pathe}")
            break()
        endif()
        
        #check children
        file(GLOB SUBDIRSS "${pathe}/*")
        FOREACH(subdir ${SUBDIRSS})
            if(IS_DIRECTORY ${subdir})
         #       message(" ---> ${subdir}")
               if("${subdir}" MATCHES "Mono(\\|/|)$")
                    message("Found mono ${subdir}")
                    set(OUT "${subdir}")
                    set(FOUND ON)
                    break()
                endif()
            endif() 
        ENDFOREACH()
        if(FOUND)
           break()
        endif()
    endforeach()
    set(${MONO_ROOT} ${OUT} PARENT_SCOPE)
 endfunction()
 
FindMon(MONO_ROOT)
message("${MONO_ROOT}")
if(NOT EXISTS "${MONO_ROOT}")
    message(FATAL_ERROR "Cannot find Mono installation dir")
 else()
    message("Copying mono dll into: ${TT_TARGET_DIR}")
    file(COPY "${MONO_ROOT}/bin/mono-2.0-sgen.dll" DESTINATION "${TT_TARGET_DIR}/")
endif()

