#pragma once
#include "ndpch.h"
#include "core/physShapes.h"
#include "block_ids.h"
//=======================GROUPs=======================

#define BLOCK_GROUP_AIR_BIT			0
#define BLOCK_GROUP_DIRT_BIT		1
#define BLOCK_GROUP_PLATFORM_BIT	2
#define BLOCK_GROUP_ORE_BIT			3



//=======================BLOCKSTATE Ids=======================
//00 BLOCK_STATE_FULL
//01 BLOCK_STATE_LINE_UP
//02 BLOCK_STATE_LINE_LEFT
//03 BLOCK_STATE_CORNER_UP_LEFT
//04 BLOCK_STATE_LINE_DOWN
//05 BLOCK_STATE_LINE_HORIZONTAL
//06 BLOCK_STATE_CORNER_DOWN_LEFT
//07 BLOCK_STATE_LINE_END_LEFT
//08 BLOCK_STATE_LINE_RIGHT
//09 BLOCK_STATE_CORNER_UP_RIGHT
//10 BLOCK_STATE_LINE_VERTICAL
//11 BLOCK_STATE_LINE_END_UP
//12 BLOCK_STATE_CORNER_DOWN_RIGHT
//13 BLOCK_STATE_LINE_END_RIGHT
//14 BLOCK_STATE_LINE_END_DOWN
//15 BLOCK_STATE_BIT

//=======================CORNER MAPPING=======================

const half_int BLOCK_CORNERS_DIRT[32] = {
	half_int(0,0),//00 BLOCK_STATE_FULL
	half_int(0,6),//01 BLOCK_STATE_LINE_UP
	half_int(0,4),//02 BLOCK_STATE_LINE_LEFT
	half_int(4,5),//03 BLOCK_STATE_CORNER_UP_LEFT
	half_int(0,5),//04 BLOCK_STATE_LINE_DOWN
	half_int(5,6),//05 BLOCK_STATE_LINE_HORIZONTAL
	half_int(6,5),//06 BLOCK_STATE_CORNER_DOWN_LEFT
	half_int(5,7),//07 BLOCK_STATE_LINE_END_LEFT
	half_int(0,3),//08 BLOCK_STATE_LINE_RIGHT
	half_int(5,5),//09 BLOCK_STATE_CORNER_UP_RIGHT
	half_int(4,6),//10 BLOCK_STATE_LINE_VERTICAL
	half_int(4,7),//11 BLOCK_STATE_LINE_END_UP
	half_int(7,5),//12 BLOCK_STATE_CORNER_DOWN_RIGHT
	half_int(7,7),//13 BLOCK_STATE_LINE_END_RIGHT
	half_int(6,7),//14 BLOCK_STATE_LINE_END_DOWN
	half_int(0,7),//15 BLOCK_STATE_BIT
	
	half_int(0+8,0),//00 CRACKED BLOCK_STATE_FULL
	half_int(0+8,6),//01 CRACKED BLOCK_STATE_LINE_UP
	half_int(0+8,4),//02 CRACKED BLOCK_STATE_LINE_LEFT
	half_int(4+8,5),//03 CRACKED BLOCK_STATE_CORNER_UP_LEFT
	half_int(0+8,5),//04 CRACKED BLOCK_STATE_LINE_DOWN
	half_int(5+8,6),//05 CRACKED BLOCK_STATE_LINE_HORIZONTAL
	half_int(6+8,5),//06 CRACKED BLOCK_STATE_CORNER_DOWN_LEFT
	half_int(5+8,7),//07 CRACKED BLOCK_STATE_LINE_END_LEFT
	half_int(0+8,3),//08 CRACKED BLOCK_STATE_LINE_RIGHT
	half_int(5+8,5),//09 CRACKED BLOCK_STATE_CORNER_UP_RIGHT
	half_int(4+8,6),//10 CRACKED BLOCK_STATE_LINE_VERTICAL
	half_int(4+8,7),//11 CRACKED BLOCK_STATE_LINE_END_UP
	half_int(7+8,5),//12 CRACKED BLOCK_STATE_CORNER_DOWN_RIGHT
	half_int(7+8,7),//13 CRACKED BLOCK_STATE_LINE_END_RIGHT
	half_int(6+8,7),//14 CRACKED BLOCK_STATE_LINE_END_DOWN
	half_int(0+8,7),//15 CRACKED BLOCK_STATE_BIT
};
const half_int BLOCK_CORNERS_GLASS[32] = {
	half_int(0,0),//00 BLOCK_STATE_FULL
	half_int(2,6),//01 BLOCK_STATE_LINE_UP
	half_int(2,4),//02 BLOCK_STATE_LINE_LEFT
	half_int(4,2),//03 BLOCK_STATE_CORNER_UP_LEFT
	half_int(2,5),//04 BLOCK_STATE_LINE_DOWN
	half_int(5,3),//05 BLOCK_STATE_LINE_HORIZONTAL
	half_int(6,2),//06 BLOCK_STATE_CORNER_DOWN_LEFT
	half_int(5,4),//07 BLOCK_STATE_LINE_END_LEFT
	half_int(2,3),//08 BLOCK_STATE_LINE_RIGHT
	half_int(5,2),//09 BLOCK_STATE_CORNER_UP_RIGHT
	half_int(4,3),//10 BLOCK_STATE_LINE_VERTICAL
	half_int(4,4),//11 BLOCK_STATE_LINE_END_UP
	half_int(7,2),//12 BLOCK_STATE_CORNER_DOWN_RIGHT
	half_int(7,4),//13 BLOCK_STATE_LINE_END_RIGHT
	half_int(6,4),//14 BLOCK_STATE_LINE_END_DOWN
	half_int(2,7),//15 BLOCK_STATE_BIT

	half_int(0+8,0),//00 CRACKED BLOCK_STATE_FULL
	half_int(2+8,6),//01 CRACKED BLOCK_STATE_LINE_UP
	half_int(2+8,4),//02 CRACKED BLOCK_STATE_LINE_LEFT
	half_int(4+8,2),//03 CRACKED BLOCK_STATE_CORNER_UP_LEFT
	half_int(2+8,5),//04 CRACKED BLOCK_STATE_LINE_DOWN
	half_int(5+8,3),//05 CRACKED BLOCK_STATE_LINE_HORIZONTAL
	half_int(6+8,2),//06 CRACKED BLOCK_STATE_CORNER_DOWN_LEFT
	half_int(5+8,4),//07 CRACKED BLOCK_STATE_LINE_END_LEFT
	half_int(2+8,3),//08 CRACKED BLOCK_STATE_LINE_RIGHT
	half_int(5+8,2),//09 CRACKED BLOCK_STATE_CORNER_UP_RIGHT
	half_int(4+8,3),//10 CRACKED BLOCK_STATE_LINE_VERTICAL
	half_int(4+8,4),//11 CRACKED BLOCK_STATE_LINE_END_UP
	half_int(7+8,2),//12 CRACKED BLOCK_STATE_CORNER_DOWN_RIGHT
	half_int(7+8,4),//13 CRACKED BLOCK_STATE_LINE_END_RIGHT
	half_int(6+8,4),//14 CRACKED BLOCK_STATE_LINE_END_DOWN
	half_int(2+8,7),//15 CRACKED BLOCK_STATE_BIT
};
const half_int WALL_CORNERS_DIRT[16] = {
	half_int(0,0),//00 BLOCK_STATE_FULL
	half_int(3,2),//01 BLOCK_STATE_LINE_UP
	half_int(2,1),//02 BLOCK_STATE_LINE_LEFT
	half_int(2,2),//03 BLOCK_STATE_CORNER_UP_LEFT
	half_int(3,0),//04 BLOCK_STATE_LINE_DOWN
	half_int(0,0),//05 BLOCK_STATE_LINE_HORIZONTAL INVALID
	half_int(2,0),//06 BLOCK_STATE_CORNER_DOWN_LEFT
	half_int(0,0),//07 BLOCK_STATE_LINE_END_LEFT INVALID
	half_int(4,1),//08 BLOCK_STATE_LINE_RIGHT
	half_int(4,2),//09 BLOCK_STATE_CORNER_UP_RIGHT
	half_int(0,0),//10 BLOCK_STATE_LINE_VERTICAL INVALID
	half_int(0,0),//11 BLOCK_STATE_LINE_END_UP INVALID
	half_int(4,0),//12 BLOCK_STATE_CORNER_DOWN_RIGHT
	half_int(0,0),//13 BLOCK_STATE_LINE_END_RIGHT INVALID
	half_int(0,0),//14 BLOCK_STATE_LINE_END_DOWN INVALID
	half_int(0,0),//15 BLOCK_STATE_BIT INVALID
};

const half_int WALL_CORNERS_GLASS[16] = {
	half_int(0+0,0),//00 BLOCK_STATE_FULL
	half_int(6+3,2),//01 BLOCK_STATE_LINE_UP
	half_int(6+2,1),//02 BLOCK_STATE_LINE_LEFT
	half_int(6+2,2),//03 BLOCK_STATE_CORNER_UP_LEFT
	half_int(6+3,0),//04 BLOCK_STATE_LINE_DOWN
	half_int(6+0,0),//05 BLOCK_STATE_LINE_HORIZONTAL INVALID
	half_int(6+2,0),//06 BLOCK_STATE_CORNER_DOWN_LEFT
	half_int(6+0,0),//07 BLOCK_STATE_LINE_END_LEFT INVALID
	half_int(6+4,1),//08 BLOCK_STATE_LINE_RIGHT
	half_int(6+4,2),//09 BLOCK_STATE_CORNER_UP_RIGHT
	half_int(6+0,0),//10 BLOCK_STATE_LINE_VERTICAL INVALID
	half_int(6+0,0),//11 BLOCK_STATE_LINE_END_UP INVALID
	half_int(6+4,0),//12 BLOCK_STATE_CORNER_DOWN_RIGHT
	half_int(6+0,0),//13 BLOCK_STATE_LINE_END_RIGHT INVALID
	half_int(6+0,0),//14 BLOCK_STATE_LINE_END_DOWN INVALID
	half_int(6+0,0),//15 BLOCK_STATE_BIT INVALID
};

const nd::Phys::Polygon BLOCK_BOUNDS_DEFAULT[3] = {
	nd::Phys::toPolygon(nd::Phys::Rectangle::createFromDimensions(0,0,1,1)),//00 BLOCK_STATE_FULL
	nd::Phys::Polygon({{0,0},{1,0},{1,1}}) ,//00 LEFT_CORNER
	nd::Phys::Polygon({{0,0},{1,0},{0,1}}) ,//00 RIGHT_CORNER
};
const nd::Phys::Polygon BLOCK_BOUNDS_DOOR = nd::Phys::toPolygon(nd::Phys::Rectangle::createFromDimensions(0.25,0,0.5,1));
const nd::Phys::Polygon BLOCK_BOUNDS_PLATFORM = nd::Phys::toPolygon(nd::Phys::Rectangle::createFromDimensions(0,0.75,1,0.25));

